// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	loadWorkout: (path: string) => __TAURI_INVOKE<ParsedWorkout>("load_workout", { path }),
	listWorkoutsCmd: (folder: string) => __TAURI_INVOKE<WorkoutLibrary>("list_workouts_cmd", { folder }),
	flattenWorkoutCmd: (workout: ParsedWorkout, ftpW: number) => __TAURI_INVOKE<FlatBlock[]>("flatten_workout_cmd", { workout, ftpW }),
	scanDevices: () => __TAURI_INVOKE<DeviceInfo[]>("scan_devices"),
	connectTrainer: (deviceId: string) => __TAURI_INVOKE<null>("connect_trainer", { deviceId }),
	connectHrm: (deviceId: string) => __TAURI_INVOKE<null>("connect_hrm", { deviceId }),
	disconnectTrainer: () => __TAURI_INVOKE<null>("disconnect_trainer"),
	disconnectHrm: () => __TAURI_INVOKE<null>("disconnect_hrm"),
	retryReconnect: (kind: DeviceKind) => __TAURI_INVOKE<null>("retry_reconnect", { kind }),
	setTargetPower: (watts: number) => __TAURI_INVOKE<null>("set_target_power", { watts }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	updateSettings: (settings: Settings) => __TAURI_INVOKE<null>("update_settings", { settings }),
	startSession: (workout: ParsedWorkout, ftpW: number) => __TAURI_INVOKE<null>("start_session", { workout, ftpW }),
	pauseSession: () => __TAURI_INVOKE<null>("pause_session"),
	resumeSession: () => __TAURI_INVOKE<null>("resume_session"),
	stopSession: () => __TAURI_INVOKE<null>("stop_session"),
	skipBlock: () => __TAURI_INVOKE<null>("skip_block"),
	reportAero: (aero: boolean | null) => __TAURI_INVOKE<null>("report_aero", { aero }),
	getSessionSnapshot: () => __TAURI_INVOKE<{
	flat_blocks: FlatBlock[],
	ftp_w: number,
	workout_name: string | null,
	workout_author: string | null,
	workout_description: string | null,
	metrics: SessionMetrics | null,
	is_ftp_test: boolean,
} | null>("get_session_snapshot"),
	listSessions: () => __TAURI_INVOKE<SessionCard[]>("list_sessions"),
	getSession: (id: number) => __TAURI_INVOKE<SessionDetail>("get_session", { id }),
	deleteSession: (id: number) => __TAURI_INVOKE<null>("delete_session", { id }),
	exportSessionTcx: (id: number, path: string) => __TAURI_INVOKE<null>("export_session_tcx", { id, path }),
	stravaStatus: () => __TAURI_INVOKE<StravaStatus>("strava_status"),
	stravaConnect: () => __TAURI_INVOKE<StravaStatus>("strava_connect"),
	stravaDisconnect: () => __TAURI_INVOKE<null>("strava_disconnect"),
	stravaSetAutoUpload: (enabled: boolean) => __TAURI_INVOKE<null>("strava_set_auto_upload", { enabled }),
	uploadSessionToStrava: (sessionId: number, force: boolean) => __TAURI_INVOKE<number>("upload_session_to_strava", { sessionId, force }),
};

/* Types */
export type BleError = {
	device: string,
	message: string,
};

export type BleMetrics = {
	power_w: number | null,
	hr_bpm: number | null,
	cadence_rpm: number | null,
};

/**
 *  Structured payload for the `ble_reconnect` event. `attempt` is only meaningful
 *  while `status == "reconnecting"`.
 */
export type BleReconnect = {
	device: string,
	status: string,
	attempt: number | null,
};

export type DeviceInfo = {
	id: string,
	name: string,
	kind: DeviceKind | null,
};

export type DeviceKind = "Trainer" | "Hrm";

export type FlatBlock = {
	duration_s: number,
	power_start_w: number,
	power_end_w: number,
	cadence_rpm: number | null,
	label: string,
};

export type Metric = {
	t_offset_s: number,
	power_w: number | null,
	hr_bpm: number | null,
	cadence_rpm: number | null,
	aero_score: number | null,
};

export type ParsedWorkout = {
	author: string | null,
	name: string | null,
	description: string | null,
	sport_type: SportType,
	workout_blocks: WorkoutBlock[],
	is_ftp_test: boolean,
	/**
	 *  Source file name (basename only). None when parsed from raw content
	 *  without a file context (e.g. tests or load_workout command).
	 */
	file_name: string | null,
};

export type SessionCard = {
	id: number,
	started_at: string,
	workout_name: string,
	duration_s: number | null,
	avg_power_w: number | null,
	avg_hr_bpm: number | null,
	avg_cadence_rpm: number | null,
	ftp_w_used: number,
	workout_type: WorkoutType | null,
	aero_pct: number | null,
	np_w: number | null,
	if_: number | null,
	tss: number | null,
};

export type SessionDetail = {
	id: number,
	strava_activity_id: number | null,
	started_at: string,
	ended_at: string | null,
	workout_name: string,
	duration_s: number | null,
	avg_power_w: number | null,
	max_power_w: number | null,
	avg_hr_bpm: number | null,
	max_hr_bpm: number | null,
	avg_cadence_rpm: number | null,
	max_cadence_rpm: number | null,
	ftp_w_used: number,
	workout_type: WorkoutType | null,
	aero_pct: number | null,
	np_w: number | null,
	if_: number | null,
	tss: number | null,
	flat_blocks: FlatBlock[],
	metrics: Metric[],
};

export type SessionMetrics = {
	state: StateKind,
	total_elapsed_s: number,
	total_active_s: number,
	current_block_idx: number,
	current_block_elapsed_s: number,
	target_w: number | null,
	cadence_target_rpm: number | null,
	power_w: number | null,
	hr_bpm: number | null,
	cadence_rpm: number | null,
	ftp_w: number,
	blocks_total: number,
	session_id: number | null,
};

export type SessionSnapshot = {
	flat_blocks: FlatBlock[],
	ftp_w: number,
	workout_name: string | null,
	workout_author: string | null,
	workout_description: string | null,
	metrics: SessionMetrics | null,
	is_ftp_test: boolean,
};

export type Settings = {
	ftp_w: number,
	max_hr_bpm: number,
	workout_path: string,
	/**  Base URL of the user's local Strava auth proxy (holds their client secret). */
	strava_proxy_url: string,
	/**  Global default for front-camera aero detection. */
	aero_enabled: boolean,
};

export type SportType = "Bike" | "Running";

export type StateKind = "WaitingForRider" | "Running" | "Paused" | "Finished";

/**  Status surfaced to the frontend. */
export type StravaStatus = {
	connected: boolean,
	athlete_id: number | null,
	athlete_name: string | null,
	auto_upload: boolean,
};

export type WorkoutBlock = ({ SteadyState: {
	duration_s: number,
	power_pct: number | null,
	cadence_rpm: number | null,
	label: string | null,
} }) & { IntervalsT?: never; Ramp?: never } | ({ Ramp: {
	duration_s: number,
	power_start_pct: number | null,
	power_end_pct: number | null,
	cadence_rpm: number | null,
	label: string | null,
} }) & { IntervalsT?: never; SteadyState?: never } | ({ IntervalsT: {
	repeat: number,
	on: WorkoutBlock,
	off: WorkoutBlock,
} }) & { Ramp?: never; SteadyState?: never };

/**  A file that could not be read or parsed, returned alongside successful workouts. */
export type WorkoutFileError = {
	file_name: string,
	message: string,
};

/**
 *  Result of listing a workout folder: successfully parsed workouts plus any
 *  files that failed (parse errors, unreadable files), so the frontend can
 *  show a warning without hiding the workouts that did load.
 */
export type WorkoutLibrary = {
	workouts: ParsedWorkout[],
	errors: WorkoutFileError[],
};

/**  Bridge enum shared with the frontend via generated bindings (src/lib/bindings.ts). */
export type WorkoutType = "Recovery" | "Endurance" | "Tempo" | "Sweet Spot" | "Threshold" | "VO2max" | "Anaerobic";

